/* 離線快取（版本號由內容自動產生）：核心檔安裝時快取，其餘檔案啟用後在背景補抓 */
var CACHE = 'gg-10ab771f5e';
var CORE = [
  './',
  'css/style.css',
  'game.html',
  'index.html',
  'js/engine.js',
  'js/games.js',
  'js/games/blocks.js',
  'js/games/breakout.js',
  'js/games/bubble.js',
  'js/games/connect4.js',
  'js/games/fishing.js',
  'js/games/flappy.js',
  'js/games/g2048.js',
  'js/games/gems.js',
  'js/games/gomoku.js',
  'js/games/hockey.js',
  'js/games/hoops.js',
  'js/games/jumper.js',
  'js/games/memory.js',
  'js/games/mines.js',
  'js/games/penalty.js',
  'js/games/racer.js',
  'js/games/runner.js',
  'js/games/snake.js',
  'js/games/space.js',
  'js/games/stairs.js',
  'js/games/tanks.js',
  'js/games/whack.js',
  'js/sw-register.js',
  'manifest.webmanifest'
];
var FILES = [
  'assets/animals/bear.png',
  'assets/animals/chick.png',
  'assets/animals/chicken.png',
  'assets/animals/cow.png',
  'assets/animals/dog.png',
  'assets/animals/duck.png',
  'assets/animals/elephant.png',
  'assets/animals/frog.png',
  'assets/animals/giraffe.png',
  'assets/animals/hippo.png',
  'assets/animals/horse.png',
  'assets/animals/monkey.png',
  'assets/animals/narwhal.png',
  'assets/animals/owl.png',
  'assets/animals/panda.png',
  'assets/animals/parrot.png',
  'assets/animals/penguin.png',
  'assets/animals/pig.png',
  'assets/animals/rabbit.png',
  'assets/animals/sloth.png',
  'assets/animals/snake.png',
  'assets/animals/walrus.png',
  'assets/animals/whale.png',
  'assets/animals/zebra.png',
  'assets/blob/blue_dizzy.png',
  'assets/blob/blue_happy.png',
  'assets/blob/green_dizzy.png',
  'assets/blob/green_happy.png',
  'assets/blob/keeper.png',
  'assets/blob/keeper_dizzy.png',
  'assets/blob/keeper_smile.png',
  'assets/blob/pink_dizzy.png',
  'assets/blob/pink_happy.png',
  'assets/blob/purple_dizzy.png',
  'assets/blob/purple_happy.png',
  'assets/blob/red_dizzy.png',
  'assets/blob/red_happy.png',
  'assets/blob/yellow_dizzy.png',
  'assets/blob/yellow_happy.png',
  'assets/blob/yellow_smile.png',
  'assets/board/chipBlackWhite.png',
  'assets/board/chipBlueWhite.png',
  'assets/board/chipBlueWhite_border.png',
  'assets/board/chipRedWhite.png',
  'assets/board/chipRedWhite_border.png',
  'assets/bunny/bg_layer2.png',
  'assets/bunny/bg_layer3.png',
  'assets/bunny/bg_layer4.png',
  'assets/bunny/cactus.png',
  'assets/bunny/carrot.png',
  'assets/bunny/carrot_gold.png',
  'assets/bunny/cloud.png',
  'assets/bunny/flyMan_fly.png',
  'assets/bunny/flyMan_still_fly.png',
  'assets/bunny/gold_1.png',
  'assets/bunny/gold_2.png',
  'assets/bunny/gold_3.png',
  'assets/bunny/gold_4.png',
  'assets/bunny/grass1.png',
  'assets/bunny/grass2.png',
  'assets/bunny/ground_cake_small.png',
  'assets/bunny/ground_grass.png',
  'assets/bunny/ground_grass_small.png',
  'assets/bunny/ground_snow_small.png',
  'assets/bunny/hero_hurt.png',
  'assets/bunny/hero_jump.png',
  'assets/bunny/hero_ready.png',
  'assets/bunny/hero_stand.png',
  'assets/bunny/hero_walk1.png',
  'assets/bunny/hero_walk2.png',
  'assets/bunny/jetpack.png',
  'assets/bunny/jetpack_item.png',
  'assets/bunny/mushroom_brown.png',
  'assets/bunny/mushroom_red.png',
  'assets/bunny/spikeMan_walk1.png',
  'assets/bunny/spikeMan_walk2.png',
  'assets/bunny/spring.png',
  'assets/bunny/springMan_stand.png',
  'assets/bunny/spring_out.png',
  'assets/bunny/wingMan1.png',
  'assets/bunny/wingMan2.png',
  'assets/bunny/wingMan3.png',
  'assets/bunny/wingMan4.png',
  'assets/covers/blocks.jpg',
  'assets/covers/breakout.jpg',
  'assets/covers/bubble.jpg',
  'assets/covers/connect4.jpg',
  'assets/covers/fishing.jpg',
  'assets/covers/flappy.jpg',
  'assets/covers/g2048.jpg',
  'assets/covers/gems.jpg',
  'assets/covers/gomoku.jpg',
  'assets/covers/hockey.jpg',
  'assets/covers/hoops.jpg',
  'assets/covers/jumper.jpg',
  'assets/covers/memory.jpg',
  'assets/covers/mines.jpg',
  'assets/covers/penalty.jpg',
  'assets/covers/racer.jpg',
  'assets/covers/runner.jpg',
  'assets/covers/snake.jpg',
  'assets/covers/space.jpg',
  'assets/covers/stairs.jpg',
  'assets/covers/tanks.jpg',
  'assets/covers/whack.jpg',
  'assets/fish/background_rock_a.png',
  'assets/fish/background_rock_b.png',
  'assets/fish/background_seaweed_a.png',
  'assets/fish/background_seaweed_c.png',
  'assets/fish/background_seaweed_e.png',
  'assets/fish/bubble_a.png',
  'assets/fish/fish_blue.png',
  'assets/fish/fish_brown.png',
  'assets/fish/fish_green.png',
  'assets/fish/fish_grey.png',
  'assets/fish/fish_orange.png',
  'assets/fish/fish_pink.png',
  'assets/fish/fish_red.png',
  'assets/fish/fish_skeleton.png',
  'assets/fish/rock_a.png',
  'assets/fish/rock_b.png',
  'assets/fish/seaweed_grass_a.png',
  'assets/fish/seaweed_green_a.png',
  'assets/fish/seaweed_green_c.png',
  'assets/fish/seaweed_orange_a.png',
  'assets/fish/seaweed_pink_a.png',
  'assets/fish/terrain_sand_a.png',
  'assets/fish/terrain_sand_top_a.png',
  'assets/icons/blocks.png',
  'assets/icons/breakout.png',
  'assets/icons/bubble.png',
  'assets/icons/connect4.png',
  'assets/icons/fishing.png',
  'assets/icons/flappy.png',
  'assets/icons/g2048.png',
  'assets/icons/gems.png',
  'assets/icons/gomoku.png',
  'assets/icons/hockey.png',
  'assets/icons/hoops.png',
  'assets/icons/jumper.png',
  'assets/icons/memory.png',
  'assets/icons/mines.png',
  'assets/icons/penalty.png',
  'assets/icons/racer.png',
  'assets/icons/runner.png',
  'assets/icons/snake.png',
  'assets/icons/space.png',
  'assets/icons/stairs.png',
  'assets/icons/tanks.png',
  'assets/icons/whack.png',
  'assets/plane/background.png',
  'assets/plane/groundGrass.png',
  'assets/plane/planeRed1.png',
  'assets/plane/planeRed2.png',
  'assets/plane/planeRed3.png',
  'assets/plane/puffLarge.png',
  'assets/plane/puffSmall.png',
  'assets/plane/rockGrass.png',
  'assets/plane/rockGrassDown.png',
  'assets/plane/starGold.png',
  'assets/puzzle/ball.png',
  'assets/puzzle/block0.png',
  'assets/puzzle/block1.png',
  'assets/puzzle/block2.png',
  'assets/puzzle/block3.png',
  'assets/puzzle/block4.png',
  'assets/puzzle/block5.png',
  'assets/puzzle/block6.png',
  'assets/puzzle/brick_blue.png',
  'assets/puzzle/brick_green.png',
  'assets/puzzle/brick_grey.png',
  'assets/puzzle/brick_purple.png',
  'assets/puzzle/brick_red.png',
  'assets/puzzle/brick_yellow.png',
  'assets/puzzle/gem_blue_diamond.png',
  'assets/puzzle/gem_blue_square.png',
  'assets/puzzle/gem_green_polygon.png',
  'assets/puzzle/gem_grey_square.png',
  'assets/puzzle/gem_purple_polygon.png',
  'assets/puzzle/gem_red_diamond.png',
  'assets/puzzle/gem_yellow_diamond.png',
  'assets/puzzle/paddle.png',
  'assets/puzzle/selector.png',
  'assets/race/barrel_blue.png',
  'assets/race/barrel_red.png',
  'assets/race/car1.png',
  'assets/race/car2.png',
  'assets/race/car3.png',
  'assets/race/car4.png',
  'assets/race/car5.png',
  'assets/race/car6.png',
  'assets/race/cone_down.png',
  'assets/race/grass.png',
  'assets/race/player.png',
  'assets/race/rock1.png',
  'assets/race/tires_red.png',
  'assets/race/tree_large.png',
  'assets/race/tree_small.png',
  'assets/run/background_color_hills.png',
  'assets/run/background_color_trees.png',
  'assets/run/bomb.png',
  'assets/run/flag_red_a.png',
  'assets/run/gem_blue.png',
  'assets/run/gem_green.png',
  'assets/run/gem_red.png',
  'assets/run/gem_yellow.png',
  'assets/run/star.png',
  'assets/run/terrain_grass_block_center.png',
  'assets/run/terrain_grass_block_top.png',
  'assets/space/bg.png',
  'assets/space/boss.png',
  'assets/space/drone.png',
  'assets/space/elaser.png',
  'assets/space/enemy1.png',
  'assets/space/enemy2.png',
  'assets/space/enemy3.png',
  'assets/space/enemy4.png',
  'assets/space/fire.png',
  'assets/space/hit_blue.png',
  'assets/space/hit_green.png',
  'assets/space/hit_red.png',
  'assets/space/laser.png',
  'assets/space/lz_blue.png',
  'assets/space/lz_green.png',
  'assets/space/lz_red.png',
  'assets/space/meteor1.png',
  'assets/space/meteor2.png',
  'assets/space/missile.png',
  'assets/space/pw_life.png',
  'assets/space/pw_power.png',
  'assets/space/pw_shield.png',
  'assets/space/shield.png',
  'assets/space/ship.png',
  'assets/space/w_beam.png',
  'assets/space/w_bomb.png',
  'assets/space/w_drone.png',
  'assets/space/w_homing.png',
  'assets/space/w_laser.png',
  'assets/space/w_lightning.png',
  'assets/space/w_spread.png',
  'assets/sport/basketball.png',
  'assets/sport/soccer.png',
  'assets/stairs/ground_grass_small.png',
  'assets/stairs/ground_sand_small.png',
  'assets/stairs/ground_sand_small_broken.png',
  'assets/stairs/ground_stone_small.png',
  'assets/stairs/ground_wood_small.png',
  'assets/stairs/p1_hurt.png',
  'assets/stairs/p1_jump.png',
  'assets/stairs/p1_ready.png',
  'assets/stairs/p1_stand.png',
  'assets/stairs/p2_hurt.png',
  'assets/stairs/p2_jump.png',
  'assets/stairs/p2_ready.png',
  'assets/stairs/p2_stand.png',
  'assets/stairs/p3_hurt.png',
  'assets/stairs/p3_jump.png',
  'assets/stairs/p3_ready.png',
  'assets/stairs/p3_stand.png',
  'assets/stairs/p4_hurt.png',
  'assets/stairs/p4_jump.png',
  'assets/stairs/p4_ready.png',
  'assets/stairs/p4_stand.png',
  'assets/tank/bulletBlue1_outline.png',
  'assets/tank/bulletRed1_outline.png',
  'assets/tank/crateMetal.png',
  'assets/tank/crateWood.png',
  'assets/tank/explosion1.png',
  'assets/tank/explosion2.png',
  'assets/tank/explosion3.png',
  'assets/tank/explosion4.png',
  'assets/tank/explosion5.png',
  'assets/tank/explosionSmoke3.png',
  'assets/tank/tank_blue.png',
  'assets/tank/tank_red.png',
  'assets/tank/tileGrass1.png',
  'assets/tank/tileSand1.png',
  'assets/ui/heart.png',
  'assets/ui/heart_empty.png',
  'assets/ui/star.png',
  'icon-180.png',
  'icon-512.png'
];
self.addEventListener('install', function (e) {
  e.waitUntil(caches.open(CACHE).then(function (c) { return c.addAll(CORE); }).then(function () { return self.skipWaiting(); }));
});
function fillRest() {
  // 一個一個慢慢抓，失敗的下次再補，不影響使用
  return caches.open(CACHE).then(function (c) {
    var i = 0;
    function next() {
      if (i >= FILES.length) return null;
      var f = FILES[i++];
      return c.match(f).then(function (hit) {
        if (hit) return null;
        return fetch(f).then(function (r) { if (r.ok) return c.put(f, r); }).catch(function () {});
      }).then(next);
    }
    return next();
  });
}
self.addEventListener('activate', function (e) {
  e.waitUntil(caches.keys().then(function (keys) {
    return Promise.all(keys.filter(function (k) { return k !== CACHE; }).map(function (k) { return caches.delete(k); }));
  }).then(function () { return self.clients.claim(); }));
  fillRest();
});
self.addEventListener('fetch', function (e) {
  var req = e.request;
  if (req.method !== 'GET' || req.url.indexOf(self.location.origin) !== 0) return;
  var code = req.mode === 'navigate' || /\.(html|js|css|webmanifest)(\?|$)/.test(req.url);
  if (code) {
    // 網頁與程式：先抓網路（拿最新版），沒網路才用快取
    e.respondWith(fetch(req).then(function (r) {
      if (r.ok) { var copy = r.clone(); caches.open(CACHE).then(function (c) { c.put(req, copy); }); }
      return r;
    }).catch(function () { return caches.match(req, { ignoreSearch: true }); }));
    return;
  }
  // 圖片：先用快取，沒有才抓網路並存起來
  e.respondWith(caches.match(req, { ignoreSearch: true }).then(function (hit) {
    return hit || fetch(req).then(function (r) {
      if (r.ok) { var copy = r.clone(); caches.open(CACHE).then(function (c) { c.put(req, copy); }); }
      return r;
    });
  }));
});
